# Generated by Django 5.0.6 on 2026-08-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_btspackage_vendor_order_city_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btspackage',
            name='budget_tier',
            field=models.CharField(choices=[('essential', 'Essential Set'), ('glow', 'Glow Set'), ('complete', 'Complete Set')], default='mid', max_length=20),
        ),
    ]
