# Generated by Django 5.2.6 on 2026-09-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_btspackage_budget_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='btspackage',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('both', 'Both / Unisex')], default='female', max_length=10),
        ),
        migrations.AlterField(
            model_name='btspackage',
            name='budget_tier',
            field=models.CharField(choices=[('essential', 'Essential Set'), ('glow', 'Glow Set'), ('complete', 'Complete Set')], default='essential', max_length=20),
        ),
    ]
