# Generated by Django 5.2.6 on 2026-09-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_btspackage_gender_alter_btspackage_budget_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='btspackage',
            name='items_list',
            field=models.TextField(blank=True, help_text='One item per line'),
        ),
    ]
