# Generated by Django 5.2.6 on 2026-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_btspackage_items_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.CharField(blank=True, help_text='Comma-separated colors e.g. Black, White, Navy Blue', max_length=300),
        ),
    ]
