# Generated by Django 5.2.6 on 2026-09-05 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_available_colors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed NGN amount', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(default=10)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('applies_to_pkg', models.ForeignKey(blank=True, help_text='Leave blank to apply to any package', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.btspackage')),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_promos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
