# Generated by Django 5.2.6 on 2026-09-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='applies_to_product',
            field=models.ForeignKey(blank=True, help_text='Set this to limit discount to one specific product only', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
