# Generated by Django 5.2.6 on 2026-09-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_promocode_applies_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='selected_size',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_size',
            field=models.TextField(blank=True),
        ),
    ]
