# Generated by Django 5.0.6 on 2026-08-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, help_text='Auto-created on registration via Paystack API', max_length=100),
        ),
    ]
